namespace DecodeQrCode.Domain.Enum;

public enum QrCodeField
{
    PAYLOAD_FORMAT_INDICATOR,
    MERCHANT_ACCOUNT_INFORMATION,
    MERCHANT_CATEGORY_CODE,
    TRANSACTION_CURRENCY,
    COUNTRY_CODE,
    MERCHANT_NAME,
    MERCHANT_CITY,
    ADDITIONAL_DATA_FIELD_TEMPLATE,
    CRC16,
    GUI,
    KEY,
    URL,
    TXID,
    ADDITIONAL_INFORMATION,
    FSS
}
